### ISSUE TITLE
Include gmock in this feedstock

### ISSUE THREAD

**Issue by emkornfield** [conda-forge/gtest-feedstock#31]
I would like to get gmock into conda-forge.  It appears that google is now packaging gmock and gtest together (at least at source level).    Would it make sense to build the artifacts here or in a separate feedstock.  I can provide a PR to add it to this one if it is acceptable.

**Comment by xhochy** [comment]
I think, we should be able to rewrite this package that it emits two packages: `gtest` and `gmock` using conda's outputs feature: https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#outputs-section

**Comment by scopatz** [comment]
Yeah, here would  be fine
