### ISSUE TITLE
Split package into 4 pieces?

### ISSUE THREAD

**Issue by wesm** [conda-forge/gtest-feedstock#38]
As a result of this package having 4 builds bundled together in one, it is difficult to use in other CMake projects using the `find_package` facility. What do you think about producing 4 artifacts for the static/shared and shared/static CRT variants?

**Comment by scopatz** [comment]
I am fine with it as long as there is a metapackage that retains the functionality and name if the current package

**Comment by xhochy** [comment]
We could split this into two packages, the static and dynamic variants. But as gmock and gtest are build in the same process, we should still retain one build with two outputs.
