### ISSUE TITLE
clobber warnings for CMake files in /lib/cmake/GTest/...

### ISSUE THREAD

**Issue by wolfv** [conda-forge/gtest-feedstock#47]
somehow both gmock and gtest seem to include the files under that directory?

**Comment by xhochy** [comment]
Should we make a third package gtest-cmake and let both depend on this?

**Comment by wolfv** [comment]
I think gmock depends on gtest so if we add it as a host-dep it might be fine, because conda deduplicates files automatically.

**Comment by wolfv** [comment]
hmm, it's kinda confusing from the docs:

## Using Google Mock Without Google Test
Google Mock is not a testing framework itself. Instead, it needs a testing framework for writing tests. Google Mock works seamlessly with Google Test, but you can also use it with any C++ testing framework.

## Requirements for End Users
Google Mock is implemented on top of Google Test, and depends on it. You must use the bundled version of Google Test when using Google Mock.
