### ISSUE TITLE
Libraries don't have a valid signature on osx-arm64

### ISSUE THREAD

**Issue by xhochy** [conda-forge/gtest-feedstock#51]
The builds produced for `osx-arm64` don't contain a valid signature as the following happens:

1. They are build with our normal toolchain which adds a signature: 
```
[cctools-port]: generating fake signature for '/Users/runner/miniforge3/conda-bld/gtest_1607640310150/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/libgtest.dylib'
```
2. `install_name_tool` is called in the post-processing of conda-build which invalidates the signature
3. On installation, no signature renewal is happening as neither a file mode is set in the metadata (`FileMode.binary` is required) as well as no prefix replacement is run as the binary doesn't contain any hard-coded paths.

This is especially bad through https://openradar.appspot.com/FB8914243 as once you have detected that you have an unsigned binary, you cannot change the signature in-place but must copy the file around once.

**Comment by xhochy** [comment]
FYI @conda-forge/help-osx-arm64

**Comment by erykoff** [comment]
I'm not sure if this is the full story.  The cctools version of install_name_tool does the signing with ldid: https://github.com/tpoechtrager/cctools-port/blob/634a084377ee2e2932c66459b0396edf76da2e9f/cctools/misc/install_name_tool.c#L324 So we should have a valid signature after running this (provided it's using cctools install_name_tool, which I suppose is a possible weak link in this chain; system install_name_tool doesn't re-sign like this).
Anyway, there might still be some complicated interplay with the openradar in that it may be an un-signable binary depending on how it was copied into place.

**Comment by xhochy** [comment]
We aren't using the cctools version of `install_name_tool` but just the one that ships with the SDK: 

```
Fixing linking of libgtest.dylib in /Users/runner/miniforge3/conda-bld/gtest_1607939533240/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/libgtest.dylib
New link location is lib/libgtest.dylib
/Applications/Xcode_12.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/runner/miniforge3/conda-bld/gtest_1607939533240/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/libgtest.dylib

/Applications/Xcode_12.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/runner/miniforge3/conda-bld/gtest_1607939533240/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/libgtest.dylib

/Applications/Xcode_12.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: /Users/runner/miniforge3/conda-bld/gtest_1607939533240/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/libgtest.dylib
```
This happens with the latest release as well as the master of `conda-build`.
